template_bucket_name: bootstrap-awss3cloudformationbucket-114n2ojlbvj21
# Sender for notification hooks
aws_account_name: Scicomp
aws_account_email: aws.scicomp@sagebase.org
# Provisioner defaults
default_key_pair: "scicomp"
default_vpc: "snowflakevpc"
